apiVersion: batch/v1
kind: Job
metadata:
  name: xolo-client-inject
spec:
  template:
    spec:
      containers:
      - name: xolo-client
        image: xolo-client
        imagePullPolicy: Never
        command: ["poetry", "run", "xolo-client", "inject", "/data/policy_to_inject.json"]
      restartPolicy: Never
  backoffLimit: 2
