apiVersion: batch/v1
kind: Job
metadata:
  name: xolo-client-update
spec:
  template:
    spec:
      containers:
      - name: xolo-client
        image: xolo-client
        imagePullPolicy: Never
        command: ["poetry", "run", "xolo-client", "update", "P12", "/data/policy_update.json"]
      restartPolicy: Never
  backoffLimit: 2
