apiVersion: apps/v1
kind: Deployment
metadata:
  name: xolo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xolo-api
  template:
    metadata:
      labels:
        app: xolo-api
    spec:
      containers:
      - name: xolo-api
        image: xolo-api
        imagePullPolicy: Never
        ports:
        - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: xolo-api
spec:
  selector:
    app: xolo-api
  ports:
  - protocol: TCP
    port: 10000
    targetPort: 10000
  type: NodePort
